In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
#set the path of the raw data
raw_data_path = os.path.join(os.path.pardir,'data','processed')
train_file_path = os.path.join(raw_data_path, 'train.csv')
test_file_path = os.path.join(raw_data_path, 'test.csv')

In [3]:
# read the data with all default parameters
train_df = pd.read_csv(train_file_path,index_col='PassengerId')
test_df = pd.read_csv(test_file_path,index_col='PassengerId')

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [5]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

In [6]:
X = train_df.loc[:,'Age':].as_matrix().astype('float')
y = train_df['Survived'].ravel()

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [7]:
print (X.shape, y.shape)

(891, 32) (891,)


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state = 0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [9]:
#average survival in train and test
print('mean survival in train {0:.3f}'.format(np.mean(y_train)))
print('mean survival in test {0:.3f}'.format(np.mean(y_test)))

mean survival in train 0.383
mean survival in test 0.385


In [10]:
import sklearn

In [11]:
sklearn.__version__

'0.19.1'

#!conda update -y scikit-learn

In [12]:
#import function
from sklearn.dummy import DummyClassifier

In [13]:
# create model
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0)

In [14]:
#train model
model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [15]:
print('score of baseline model : {0:.2f}'.format(model_dummy.score(X_test,y_test)))

score of baseline model : 0.61


In [16]:
#performance matrix
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [17]:
#accuracy score
print('accuracy for baseline model : {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test))))

accuracy for baseline model : 0.61


In [18]:
print('confusion matrix for baseline model : \n {0}'.format(confusion_matrix(y_test, model_dummy.predict(X_test))))

confusion matrix for baseline model : 
 [[110   0]
 [ 69   0]]


In [19]:
print('precision score for baseline model : {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test))))
print('recall score for baseline model : {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test))))

precision score for baseline model : 0.00
recall score for baseline model : 0.00


D:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [20]:
test_X = test_df.as_matrix().astype('float')

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [21]:
predictions =model_dummy.predict(test_X)

In [22]:
df_submission = pd.DataFrame({'PassengerId' : test_df.index, 'Survived':predictions})

In [23]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [24]:
submission_data_path = os.path.join(os.path.pardir,'data','external')
submission_file_path = os.path.join(submission_data_path,'01_dummy.csv')

In [25]:
df_submission.to_csv(submission_file_path, index=False)

In [26]:
def get_submission_file(model, filename) :
    test_X = test_df.as_matrix().astype('float')
    predictions =model.predict(test_X)
    df_submission = pd.DataFrame({'PassengerId' : test_df.index, 'Survived':predictions})
    submission_data_path = os.path.join(os.path.pardir,'data','external')
    submission_file_path = os.path.join(submission_data_path,filename)
    df_submission.to_csv(submission_file_path, index=False)

In [27]:
get_submission_file(model_dummy, '01_dummy.csv')

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
#create model
model_lr_l = LogisticRegression(random_state=0)

In [30]:
#train model
model_lr_l.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [31]:
#evaluate model
print('score for logistic regression - version 1 : {0:2f}'.format(model_lr_l.score(X_test,y_test)))

score for logistic regression - version 1 : 0.832402


In [32]:
#accuracy score
print('accuracy for logistic regressio model - version 1 : {0:.2f}'.format(accuracy_score(y_test, model_lr_l.predict(X_test))))
print('confusion matrix for logistic regressio model - version 1: \n {0}'.format(confusion_matrix(y_test, model_lr_l.predict(X_test))))
print('precision score for logistic regressio model - version 1: {0:.2f}'.format(precision_score(y_test, model_lr_l.predict(X_test))))
print('recall score for logistic regressio model - version 1: {0:.2f}'.format(recall_score(y_test, model_lr_l.predict(X_test))))

accuracy for logistic regressio model - version 1 : 0.83
confusion matrix for logistic regressio model - version 1: 
 [[95 15]
 [15 54]]
precision score for logistic regressio model - version 1: 0.78
recall score for logistic regressio model - version 1: 0.78


In [33]:
model_lr_l.coef_

array([[-0.02739381,  0.00454634, -0.46452552,  0.        , -0.88205169,
         0.131966  , -0.16744322, -0.41217561,  0.49238372,  1.10218268,
         0.38466458, -0.13002342, -0.30622354,  0.94772181,  0.49773319,
        -0.35012381,  0.26024267,  1.17742319,  0.48924931, -1.44589457,
         1.2278909 , -0.12814411, -0.4854362 ,  0.17042578,  0.24486076,
         0.27822397,  0.40182068,  0.49000939,  0.46364626,  0.14167555,
         0.39283951,  0.70249168]])

In [34]:
get_submission_file(model_lr_l, '02_lr.csv')

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [35]:
model_lr = LogisticRegression(random_state=0)

In [36]:
from sklearn.model_selection import GridSearchCV

In [40]:
parameters = {'C':[1.0,10.0,50.0,100.0,1000.0],'penalty':['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)

In [41]:
clf.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [42]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [43]:
print('best score : {0:.2f}'.format(clf.best_score_))

best score : 0.83


In [45]:
print('score for logistic regression - version 2 :{0:.2f}'.format(clf.score(X_test,y_test)))

score for logistic regression - version 2 :0.83


In [46]:
#Making 3rd submission on Kaggle
get_submission_file(clf,'03_lr.csv')

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [48]:
#Feature Normalization And Standardization 
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [50]:
scaler =  MinMaxScaler()
X_train_scaled =scaler.fit_transform(X_train)

In [51]:
X_train_scaled[:,0].min(),X_train_scaled[:,0].max()

(0.0, 1.0)

In [52]:
X_test_scaled =scaler.transform(X_test)

In [53]:
model_lr = LogisticRegression(random_state=0)    
parameters = {'C':[1.0,10.0,50.0,100.0,1000.0],'penalty':['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)
clf.fit(X_train_scaled, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [54]:
clf.best_score_

0.8286516853932584

In [57]:
print('score for logistic regression - version 2 :{0:.2f}'.format(clf.score(X_test_scaled,y_test)))

score for logistic regression - version 2 :0.82


<b> PICKLE to save model

In [59]:
import pickle

In [72]:
model_file_path = os.path.join(os.path.pardir,'models','lr_model.pkl')
scaler_file_path = os.path.join(os.path.pardir,'models','lr_scaler.pkl')

In [73]:
model_file_pickle = open(model_file_path, 'wb')
scaler_file_pickle = open(scaler_file_path, 'wb')

In [74]:
#persist
pickle.dump(clf,model_file_pickle)
pickle.dump(scaler,scaler_file_pickle)

In [75]:
#close the file
model_file_pickle.close()
scaler_file_pickle.close()

In [76]:
model_file_pickle = open(model_file_path,'r')
scaler_file_pickle = open(scaler_file_path,'r')
clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle)
model_file_pickle.close()
scaler_file_pickle.close()

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 51: character maps to <undefined>